### ISSUE TITLE
Remove requirement for re

### ISSUE THREAD

**Issue by caternuson** [adafruit/Adafruit_CircuitPython_Pypixelbuf#8]
I made a mpy-cross of the lib to test out on a Gemma M0, but then ran into issue with `re` module:

```python
Adafruit CircuitPython 4.1.2 on 2019-12-18; Adafruit Gemma M0 with samd21e18
>>> import neopixel
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "neopixel.py", line 38, in <module>
  File "adafruit_pypixelbuf.py", line 32, in <module>
ImportError: no module named 're'
>>> 
```

**Comment by caternuson** [comment]
Fixed by #6
